/* Render the 30-second Noble Polyhedra film from stage.html. */
const http = require('http'), fs = require('fs'), path = require('path'), { spawn } = require('child_process');
let chromium;
try { ({ chromium } = require('playwright')); } catch (e) { ({ chromium } = require('playwright-core')); }
const ROOT = path.join(__dirname, '..', '..'), STILLS = path.join(__dirname, 'stills');
const TYPES = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css' };
function serve(){const server=http.createServer((req,res)=>{let file=path.join(ROOT,decodeURIComponent(req.url.split(/[?#]/)[0]));fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':TYPES[path.extname(file)]||'application/octet-stream'});res.end(data);});});return new Promise(resolve=>server.listen(0,()=>resolve(server)));}
async function launch(){const opts={args:['--force-color-profile=srgb','--hide-scrollbars']};if(process.env.CHROMIUM)return chromium.launch({...opts,executablePath:process.env.CHROMIUM});try{return await chromium.launch(opts);}catch(e){return chromium.launch({...opts,channel:'chrome'});}}
function run(cmd,args,input){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:[input?'pipe':'ignore','inherit','inherit']});p.on('error',reject);p.on('close',code=>code?reject(new Error(cmd+' failed')):resolve());if(input)Promise.resolve(input(p.stdin)).catch(e=>{p.kill();reject(e);});});}
(async()=>{const args=process.argv.slice(2),server=await serve(),browser=await launch();try{const page=await browser.newPage({viewport:{width:540,height:540},deviceScaleFactor:2});page.on('pageerror',e=>console.error('page error:',e.message));await page.goto('http://localhost:'+server.address().port+'/tools/noble-video/stage.html');await page.waitForFunction(()=>window.stageReady);const info=await page.evaluate(()=>window.stageInfo),draw=n=>page.evaluate(k=>window.frame(k),n),shot=()=>page.screenshot({type:'png'}),started=Date.now();
if(args[0]==='--stills'||args[0]==='--sheet'){const seconds=args[0]==='--sheet'?Array.from({length:20},(_,i)=>i*1.5):args[1].split(',').map(Number),names=[];fs.mkdirSync(STILLS,{recursive:true});for(let i=0;i<seconds.length;i++){const n=Math.min(info.frames-1,Math.round(seconds[i]*info.fps));await draw(n);const name=args[0]==='--sheet'?'sheet-'+String(i).padStart(2,'0')+'.png':'t'+seconds[i].toFixed(2)+'.png';fs.writeFileSync(path.join(STILLS,name),await shot());names.push(name);}if(args[0]==='--sheet'){await run('ffmpeg',['-loglevel','error','-y','-framerate','1','-i',path.join(STILLS,'sheet-%02d.png'),'-vf','scale=360:360,tile=5x4:padding=8:color=#16161a','-frames:v','1','-q:v','3',path.join(STILLS,'sheet.jpg')]);console.log('stills/sheet.jpg');}else console.log(names.join('\n'));}
else{const out=path.resolve(args[0]||path.join(__dirname,'noble-polyhedra.mp4'));await run('ffmpeg',['-loglevel','error','-y','-f','image2pipe','-c:v','png','-framerate',String(info.fps),'-i','-','-vf','scale=out_color_matrix=bt709:out_range=tv','-c:v','libx264','-preset','slow','-crf','17','-pix_fmt','yuv420p','-profile:v','high','-g',String(2*info.fps),'-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-movflags','+faststart',out],async stdin=>{for(let n=0;n<info.frames;n++){await draw(n);if(!stdin.write(await shot()))await new Promise(r=>stdin.once('drain',r));if(n%60===0)process.stdout.write('\rframe '+n+' of '+info.frames);}stdin.end();});console.log('\r'+path.relative(process.cwd(),out)+': '+info.frames+' frames at '+info.fps+' fps');}
console.log('took '+Math.round((Date.now()-started)/1000)+' s');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1);});
