/* Build the browser catalogue from the author's OFF model library.
   Run from the repository root: node tools/noble/build-models.js */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const modelDir = path.join(root, 'app', 'noble', 'models');
const paperCatalogue = JSON.parse(fs.readFileSync(path.join(__dirname, 'paper-catalogue.json'), 'utf8'));

function parseOff(text) {
  const lines = text.split(/\r?\n/).map(line => line.replace(/#.*/, '').trim()).filter(Boolean);
  if (lines.shift() !== 'OFF') throw new Error('Not an OFF file');
  const [vertexCount, faceCount] = lines.shift().split(/\s+/).map(Number);
  const vertices = lines.splice(0, vertexCount).map(line => line.split(/\s+/).slice(0, 3).map(Number));
  const faces = lines.slice(0, faceCount).map(line => {
    const values = line.split(/\s+/).map(Number);
    return values.slice(1, values[0] + 1);
  });
  return { vertices, faces };
}

function symmetryFor(name) {
  const stem = name.split('-')[0];
  if (/^[T]|T$/.test(stem)) return 'tetrahedral';
  if (/[OC]$/.test(stem)) return 'octahedral';
  return 'icosahedral';
}

function edgeCount(faces) {
  const edges = new Set();
  for (const face of faces) for (let i = 0; i < face.length; i++) {
    const a = face[i], b = face[(i + 1) % face.length];
    edges.add(a < b ? `${a}:${b}` : `${b}:${a}`);
  }
  return edges.size;
}

function compareNames(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
}

const files = fs.readdirSync(modelDir).filter(file => file.endsWith('.off')).sort(compareNames);
const models = files.map(file => {
  const name = path.basename(file, '.off');
  const geometry = parseOff(fs.readFileSync(path.join(modelDir, file), 'utf8'));
  const p = geometry.faces[0].length;
  const edges = edgeCount(geometry.faces);
  const q = 2 * edges / geometry.vertices.length;
  return {
    name,
    file: `models/${file}`,
    symmetry: symmetryFor(file),
    vertices: geometry.vertices.length,
    edges,
    faces: geometry.faces.length,
    p,
    q,
    ...paperCatalogue[name],
    geometry
  };
});

if (models.length !== 146) throw new Error(`Expected 146 models, found ${models.length}`);
const output = `/* Generated by tools/noble/build-models.js. */\nwindow.NOBLE_MODELS=${JSON.stringify(models)};\n`;
fs.writeFileSync(path.join(root, 'app', 'noble', 'models.js'), output);
console.log(`Wrote ${models.length} models to app/noble/models.js`);
